import Head from "next/head";
import {
  
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import code from "../public/code.png";
import design from "../public/design.png";
import Image from "next/image";
import Barath from "../public/Barath.jpg";
import FoodApp from "../public/Food App.PNG";
import Nike from "../public/Nike Landing.PNG";
import Calc from "../public/Idea Pixelator - Calculator.PNG";
import Page from "../public/Idea Pixelator.PNG";
import Tennis from "../public/Idea Pixelator - Tennis Game.PNG";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Barathramana C - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/code.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">

      {/* Nav Bar */}
          
      <nav className="py-10 mb-12 flex justify-between  dark:text-white">
            <h1 className="font-burtons text-xl">Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://docs.google.com/document/d/1FJ62y9keSvgPsERNxgivpox61XxB4BSO/edit?usp=drivesdk&ouid=114816768149013258932&rtpof=true&sd=true"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <section class=" shadow-lg  dark:bg-gray-800 rounded-2xl p-5 mb-5">
          <section className="min-h-screen">
          {/* Profile */}
          <div className="text-center p-10 py-10">
            <h2 className="text-2xl font-burtons py-2 text-teal-600 font-extrabold dark:text-teal-400 md:text-6xl">
              Barathramana C
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and Designer.
            </h3>
            <p className="text-md py-5 text-xl leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for Websites and design content
              needs. Take a look at my Linkedin and GitHub Profile
            </p>
            <div className="text-5xl flex justify-center gap-16 py-1 text-gray-600 dark:text-gray-400">
              <a className="text-gray-500" href="https://www.linkedin.com/in/barathramana-c-082b941bb/">
                  <AiFillLinkedin className="cusor-pointer" href="" /> 
              </a>
              
              <a class="text-gray-500" href="https://github.com/Barathram3003">
                  <AiFillGithub className="cusor-pointer" href="" />
              </a>
            </div>
            
          </div>
          <div className="mx-auto flex items-center bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={Barath}  layout="fill" objectFit="cover" />
        </div>
        </section>    
       </section>



        <section>
         {/* Services */} 
        <div class="py-16 lg:py-28">
        <h2 class="text-center text-gray-800 dark:text-white text-3xl lg:text-5xl font-bold">
          Services I offer
        </h2>
        <p class="lg:w-1/2 text-gray-800 dark:text-white text-center text-xl mx-auto mt-5">
           As the beginning of my journey as a freelance designer and
              developer, I could Offer
              <span className="text-teal-500"> Web Develepment </span>
                and <span className="text-teal-500"> Design </span>
                 for your Business.
          </p>
          <p className="lg:w-1/2 text-gray-800 dark:text-white text-center text-xl mx-auto mt-5">
          I offer from a wide range of services, including brand design and
              programming
          </p>
          </div>
          
        {/* Services Context */}
        <div class="flex flex-wrap pb-4  justify-center">
          <div class="w-full lg:w-1/2 xl:w-1/3 py-5 lg:p-5">
            <div class="bg-white p-10 rounded-2xl shadow-lg flex flex-col items-center dark:bg-gray-800">
            <Image src={design} width={100} height={100} />
                <p className="text-2xl  pt-8 pb-2 text-teal-600  dark:text-teal-600 font-bold ">
                  Beautiful Designs
                </p>
                <p className="py-2 dark:text-white text-xl ">
                  Creating elegant designs suited for your needs following core
                  design theory.
                </p>
                <h4 className="py-4 text-teal-600 text-2xl">Design Tools I Use</h4>
                <p className=" dark:text-white py-1 text-xl">Photoshop</p>
                <p className=" dark:text-white py-1 text-xl">Illustrator</p>
                <p className=" dark:text-white py-1 text-xl">Figma</p>
            </div>
          </div>

          <div class="w-full lg:w-1/2 xl:w-1/3 py-5 lg:p-5">
            <div class=" dark:bg-gray-800 p-10 rounded-2xl shadow-lg flex flex-col items-center">
              <Image src={code} width={100} height={100} />
                <p className="text-2xl  pt-8 pb-2 text-teal-600  dark:text-teal-600 font-bold ">
                  Make your Website
                </p>
                <p className="py-2 dark:text-white text-xl">
                  Do you have an idea for your next great website? Let's make it a
                  reality.
                </p>
                <h4 className="py-4 text-teal-600 text-2xl"> Languages I Use</h4>
                <p className=" dark:text-white py-1 text-xl">React JS</p>
                <p className=" dark:text-white py-1 text-xl">Next Js</p>
                <p className=" dark:text-white py-1 text-xl">Tailwind CSS</p>
            </div>
          </div>
        </div>
        {/* Contact Me  */}
        <section class="rounded-2xl lg:p-5 mb-10 p-10  ">
           <div class="container text-white mx-auto rounded-3xl bg-gradient-to-r from-purple-400 to-red-500">
              <div class="py-16 lg:py-18">
                <h2 class="text-center text-3xl lg:text-5xl font-bold">
                  Let's do something amazing
                </h2>
                <p class="lg:w-1/2 text-center mx-auto mt-2">
                  For Your Business
                </p>
                <div class="flex mt-8">
                  <button class="mx-auto bg-white p-2 px-3 rounded-2xl text-purple-900 font-semibold text-lg"><a href="#contact">Contact Me</a></button>
                </div>
              </div>
            </div>
        </section>
          
        </section>


        <section className="py-5">
          <div>
          {/*Projects Heading */}
          <div class="py-4 lg:py-28">
            <h2 class="text-center text-gray-800 dark:text-white  text-3xl lg:text-5xl font-bold">
              Projects Done By Myself
            </h2>
            <p class="lg:w-1/2 text-gray-800 dark:text-white text-center mx-auto mt-5">
                As a Learner I Created Some Projects While Learning
              
            </p>
            <p className="lg:w-1/2 text-gray-800 dark:text-white text-center mx-auto mt-5">
              You Can Check It Out 
          </p>
          </div>
            
            {/* Project Context */}
            <div className=" grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">
            <div className=" text-center shadow-lg hover:bg-gray-200 p-10 rounded-xl my-10 dark:bg-gray-800  flex-1">
              <Image src={FoodApp} width={200} height={150} />
              <h2 class="mt-3 text-xl font-bold  dark:text-teal-500">Food Deliver Application</h2>
              <ul class="flex justify-center mt-4">
              <li class="p-2 bg-white shadow rounded  mx-1">
              <a class=" text-3xl" href="https://github.com/Barathram3003/food-app-reactjs.git">
                  <AiFillGithub className="cusor-pointer" href="" />
              </a>
              </li>
              </ul>
                
            </div>

            <div className=" hover:bg-gray-200 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
              <Image src={Nike} width={200} height={150} />
              <h2 class="mt-3 text-xl font-bold  dark:text-teal-500"> Shoe Landing Page</h2>
              <ul class="flex justify-center mt-4">
              <li class="p-2 bg-white shadow rounded  mx-1">
              <a class=" text-3xl" href="https://github.com/Barathram3003/Nike-Landing-Page.git">
                  <AiFillGithub className="cusor-pointer" href="" />
              </a>
              </li>
              </ul> 
            </div>

            <div className="hover:bg-gray-200 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
              <Image src={Calc} width={200} height={150} />
              <h2 class="mt-3 text-xl font-bold  dark:text-teal-500"> EB Calculator & Length Converter</h2>
              <ul class="flex justify-center mt-4">
              <li class="p-2 bg-white shadow rounded  mx-1">
              <a class=" text-3xl" href="https://github.com/Barathram3003/Idea-Pixelator---Calculator.git">
                  <AiFillGithub className="cusor-pointer" href="" />
              </a>
              </li>
              </ul> 
            </div>

            <div className="hover:bg-gray-200 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
              <Image src={Tennis} width={200} height={150} />
              <h2 class="mt-3 text-xl font-bold  dark:text-teal-500">Tennis Game</h2>
              <ul class="flex justify-center mt-4">
              <li class="p-2 bg-white shadow rounded  mx-1">
              <a class=" text-3xl" href="https://github.com/Barathram3003/Tennis---Game.git">
                  <AiFillGithub className="cusor-pointer" href="" />
              </a>
              </li>
              </ul> 
            </div>

            <div className="hover:bg-gray-200 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
              <Image src={Page} width={200} height={150} />
              <h2 class="mt-3 text-xl font-bold  dark:text-teal-500">Idea Pixelator Page</h2>
              <ul class="flex justify-center mt-4">
              <li class="p-2 bg-white shadow rounded  mx-1">
              <a class=" text-3xl" href="https://github.com/Barathram3003/Idea-pixelator---Landing-Page-.git">
                  <AiFillGithub className="cusor-pointer" href="" />
              </a>
              </li>
              </ul> 
            </div>

            <div className="hover:bg-gray-200 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
              <Image src={FoodApp} width={200} height={150} />
              <h2 class="mt-3 text-xl font-bold  dark:text-teal-500">Food Delivery Application Version-2</h2>
              <ul class="flex justify-center mt-4">
              <li class="p-2 bg-white shadow rounded  mx-1">
              <a class=" text-3xl" href="https://github.com/Barathram3003/food-app-2-reactjs.git">
                  <AiFillGithub className="cusor-pointer" href="" />
              </a>
              </li>
              </ul>  
            </div>

            </div>
            
            
          </div>
          
        </section>

        <section id="contact">
          <section class=" shadow-lg  hover:bg-gray-200 dark:bg-gray-800 rounded-2xl p-5 mb-10">
            <div class="container mx-auto">
              <div class="py-8 lg:py-14">
                <h2 class="text-center  dark:text-white text-3xl lg:text-5xl font-bold">
                  Contact Me
                </h2>
        
               </div>
      
            <div class="mb-14 lg:w-1/2 mx-auto">
              <form action="https://api.web3forms.com/submit" method="POST">
            <div>
            <input type="hidden" name="access_key" value="bb473f0d-77f1-4ea1-9cb9-da8b0addbf1d" />
              <div class="flex  bg-white dark:bg-gray-800 p-2 rounded  ">
                <div class="w-auto flex px-2 dark:text-white">
                  <svg xmlns="http://www.w3.org/2000/svg" class="my-auto h-6 w-6" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                  </svg>
                </div>

                <div class="w-full">
                  <span class="block  text-black-300 dark:text-white">Enter your Name</span>
                  <input class="w-full p-1 focus:outline-none border-b" name="name" type="text" required />
                </div>
              </div>
              <div class="flex mt-3 bg-white dark:bg-gray-800 p-2 rounded ">
                <div class="w-auto flex px-2 dark:text-white">
                  <svg xmlns="http://www.w3.org/2000/svg" class="my-auto h-6 w-6" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207" />
                  </svg>
              </div>
              <div class="w-full" id="email">
                <span  class="block dark:text-white">Enter your Email</span>
                <input class="w-full p-1 focus:outline-none border-b" name="email" type="email" required />
              </div>
            </div>
            <div class="flex mt-3 bg-white p-2 rounded dark:bg-gray-800  ">
              <div class="w-auto flex px-2 dark:text-white">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 13.5L12 21m0 0l-7.5-7.5M12 21V3" />
                </svg>
              
              </div>
              <div class="w-full">
                <span class="block dark:text-white">Select Service</span>
                <select class="w-full p-1 focus:outline-none border-b" name="service" id="" required>
                  <option value="Design" >Design</option>
                  <option value="Web Development"  >Web Development</option>
                  <option value="Digital Marketing" >Digital Marketing</option>
                  <option value="Logo" >Logo Creation</option>
                  </select>
                </div>
              </div>
            <div class="flex mt-3  bg-white p-2 rounded dark:bg-gray-800  ">
              <div class="w-auto flex px-2 dark:text-white">
                <svg xmlns="http://www.w3.org/2000/svg" class="my-auto h-6 w-6" fill="none" viewBox="0 0 24 24"
                  stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M8 12h.01M12 12h.01M16 12h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <div class="w-full">
                <span class="block  dark:text-white">Enter your Message</span>
                <textarea class="w-full p-1 focus:outline-none border-b" name="message" rows="" cols=""></textarea>
              </div>
          </div>
          <div class="flex mt-8">
                  <button class="mx-auto  bg-teal-600 p-2 px-3 rounded-2xl text-white font-semibold text-lg" type="submit">Submit</button>
                </div>
          </div>
        </form>
      </div>
    </div>
    </section>
        </section>


        {/* Footer */}

        <footer className="dark:text-white shadow-lg rounded-3xl p-5 dark:bg-gray-800">
            <div className="flex flex-wrap py-12">
                <div className="p-5 lg:p-10 w-full md:w-1/3">
                <h2 className=" py-2 lg:text-3xl font-burtons text-teal-600 font-semibold dark:text-teal-400">
                  Barathramana C
                </h2>
                <h1 className=" py-2 dark:text-white">
                  Developer and Designer.
                </h1>
                  <p className="dark:text-white mt-3">
                    Freelancer providing services for Websites and design
                  </p>
                </div>
                <div class="p-5 lg:p-10 w-full md:w-1/3">
                  <h2 class="font-extrabold text-teal-600 text-xl">Address</h2>
                    <p class="dark:text-white mt-3">
                      Salem<br />
                      Tamil Nadu<br />
                      India<br />
                      Pin-636453
                    </p>
                </div>
                <div class="p-5 lg:p-10 w-full md:w-1/3">
                    <h2 class="font-extrabold text-teal-600 text-xl">Inquiries</h2>
                    <p class="dark:text-white mt-3">
                        <a href="tel:+919791496683">9791496683</a>
                    </p> 
                    <a href="mailto:barathramana3003@gmail.com">barathramana3003@gmail.com</a>     
                    <ul class="flex mt-4">
                      <li class="p-2 bg-white shadow rounded  mx-1">
                        <a className="text-gray-500 text-2xl" href="https://www.linkedin.com/in/barathramana-c-082b941bb/">
                          <AiFillLinkedin className="cusor-pointer" href="" /> 
                        </a>
                      </li>
                      <li class="p-2 bg-white shadow rounded  mx-1">
                        <a class="text-gray-500 text-2xl" href="https://github.com/Barathram3003">
                          <AiFillGithub className="cusor-pointer" href="" />
                        </a>
                      </li>
                    </ul>                  
                  </div>
            </div>
            <div class="text-center text-gray-500 border-t border-gray-500 pt-3">
                All Rights Reserved
            </div>
        </footer>

      </main>
    </div>
  );
}
